version: '3.8'

services:
  dito:
    build:
      context: .
      dockerfile: Dockerfile
    image: dito:latest
    container_name: dito-proxy
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    volumes:
      # Optional: mount custom config for local development
      - ./config.local.yaml:/app/config.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dito-network
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /app/tmp
      - /app/logs

  # Optional: Add a simple nginx for testing
  test-backend:
    image: nginx:alpine
    container_name: dito-test-backend
    ports:
      - "8080:80"
    volumes:
      - ./test-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - dito-network

networks:
  dito-network:
    driver: bridge
    name: dito-network

# Optional: Add volumes for persistent data
volumes:
  dito-logs:
    driver: local
