package e2e

// Errors towards the backend: the proxy answers with its JSON error.

import (
	"context"
	"fmt"
	"net/http"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// assertProxyError checks status and envelope of an error generated by the proxy.
func assertProxyError(s *S, r *Response, status int) proxyError {
	require.NoError(s, r.Err)
	assert.Equal(s, status, r.Status)
	e, err := r.ProxyError()
	require.NoError(s, err, "the error body is valid JSON: %q", r.Body())
	assert.Equal(s, status, e.Error.Code)
	assert.NotEmpty(s, e.RequestID)
	return e
}

func TestErrors_BackendUnreachable(t *testing.T) {
	Run(t, func(s *S) {
		port, err := freePort() // nothing listens on it any more
		require.NoError(s, err)
		p := s.Proxy(fmt.Sprintf(`
  - path: "^/down$"
    target_url: "http://127.0.0.1:%d/"
    replace_path: true`, port))
		e := assertProxyError(s, s.Get(p.URL+"/down"), http.StatusBadGateway)
		assert.NotEmpty(s, e.Error.Details["upstream_error"])
	})
}

func TestErrors_BackendTimeout(t *testing.T) {
	Run(t, func(s *S) {
		s.Backend("slow", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			select {
			case <-r.Context().Done():
			case <-time.After(5 * time.Second):
			}
		}))
		p := s.Proxy(`
  - path: "^/slow$"
    target_url: "{{backend "slow"}}/"
    replace_path: true`, WithTransport("dial_timeout: 2s\nresponse_header_timeout: 300ms"))
		assertProxyError(s, s.Get(p.URL+"/slow"), http.StatusGatewayTimeout)
	})
}

func TestErrors_InvalidTarget(t *testing.T) {
	Run(t, func(s *S) {
		p := s.Proxy(`
  - path: "^/broken$"
    target_url: "http://"
    replace_path: true`)
		assertProxyError(s, s.Get(p.URL+"/broken"), http.StatusInternalServerError)
	})
}

func TestErrors_ClientCancels(t *testing.T) {
	Run(t, func(s *S) {
		started := make(chan struct{})
		canceled := make(chan struct{})
		s.Backend("slow", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			close(started)
			select {
			case <-r.Context().Done():
				close(canceled)
			case <-time.After(10 * time.Second):
			}
		}))
		p := s.Proxy(`
  - path: "^/slow$"
    target_url: "{{backend "slow"}}/"
    replace_path: true`)
		ctx, cancel := context.WithCancel(context.Background())
		defer cancel()
		go func() {
			<-started
			cancel()
		}()
		r := s.Do(s.NewRequest(http.MethodGet, p.URL+"/slow", nil).WithContext(ctx))
		assert.Error(s, r.Err, "the client gave up")
		select {
		case <-canceled:
		case <-time.After(3 * time.Second):
			assert.Fail(s, "the backend request is not canceled when the client goes away")
		}
	})
}
