# Configuration for the proxy server.
port: '8081' # The port on which the server will listen.
hot_reload: true # Enable hot reloading of the configuration file.

# Logging configuration.
logging:
  enabled: true # Enable or disable logging.
  verbose: false # Enable or disable verbose logging.
  level: "info" # Set the log level (e.g., debug, info, warn, error)

# Metrics configuration.
metrics:
  enabled: true # Enable or disable metrics.
  path: "/metrics" # The path on which the metrics will be exposed.

# Redis configuration.
redis:
  enabled: false # Enable or disable Redis caching.
  host: "localhost"
  port: "6379"
  password: ""  # Leave empty if no password is required.

# Transport configuration.
transport:
  http:
    idle_conn_timeout: 90s
    max_idle_conns: 1000
    max_idle_conns_per_host: 200
    max_conns_per_host: 0
    tls_handshake_timeout: 2s
    response_header_timeout: 2s
    expect_continue_timeout: 500ms
    disable_compression: false
    dial_timeout: 2s
    keep_alive: 30s
    force_http2: true
    #cert_file: "/home/andy/dev/personal/api-test/client_cert.pem" # Optional client certificate file for HTTPS connections.
    #key_file: "/home/andy/dev/personal/api-test/client_key.pem" # Optional client key file for HTTPS connections.
    #ca_file: "/home/andy/dev/personal/api-test/test_ca.pem" # Optional CA certificate file for verifying server certificates.



# List of location configurations for proxying requests.
locations:
  - path: "^/test-ws$"
    target_url: "wss://echo.websocket.org"
    enable_websocket: true n
    replace_path: true

  - path: "^/dito$" # Regex pattern to match the request path.
    target_url: https://httpbin.org/get
    enable_websocket: true # Enable or disable WebSocket support.
    # The target URL to which the request will be proxied.
    replace_path: true # Replace the matched path with the target URL.


    additional_headers:
      # Additional headers to be added to the request.
      il-molise: non esiste ancora
    excluded_headers:
      #- Cookie # Headers to be excluded from the request.
    middlewares:
      #- rate-limiter-redis
      #- auth
      #- cache
    rate_limiting:
      enabled: false
      requests_per_second: 2
      burst: 4
    cache:
      enabled: false
      ttl: 30


  - path: "^/todos/(?:[1-9]|10)$" # Regex pattern to match the request path.
    target_url: https://jsonplaceholder.typicode.com/ # The target URL to which the request will be proxied.
    additional_headers:
      Host: jsonplaceholder.typicode.com # Additional headers to be added to the request.
    middlewares:
      - auth
      #- rate-limiter-redis
    rate_limiting:
      enabled: true
      requests_per_second: 2
      burst: 4
    excluded_headers:
      - Cookie # Headers to be excluded from the request.


