# Configuration for the proxy server.
port: "8081" # The port on which the server will listen.
hot_reload: true # Enable hot reloading of the configuration file.
request_timeout: 30s # Timeout for requests to the target server.

# Logging configuration.
logging:
  enabled: true # Enable or disable logging.
  verbose: false # Enable or disable verbose logging.
  level: "info" # Set the log level (e.g., debug, info, warn, error)

# Metrics configuration.
metrics:
  enabled: true # Enable or disable metrics.
  path: "/metrics" # The path on which the metrics will be exposed.

# Global response limits configuration (for testing).
response_limits:
  max_response_body_size: 100000 # 100KB default limit

plugins:
  directory: "./plugins"
  public_key_path: "./ed25519_public.key"
  public_key_hash: "1e4d1e5942f260083293d09c22fecc8109d7a11b6a087bb3ef9da20086b16101" # Hash of the public key for plugin verification.


# Transport configuration.
transport:
  http:
    idle_conn_timeout: 90s
    max_idle_conns: 1000
    max_idle_conns_per_host: 200
    max_conns_per_host: 0
    tls_handshake_timeout: 2s
    response_header_timeout: 2s
    expect_continue_timeout: 500ms
    disable_compression: false
    dial_timeout: 2s
    keep_alive: 30s
    force_http2: true
    #cert_file: "/home/andy/dev/personal/api-test/client_cert.pem" # Optional client certificate file for HTTPS connections.
    #key_file: "/home/andy/dev/personal/api-test/client_key.pem" # Optional client key file for HTTPS connections.
    #ca_file: "/home/andy/dev/personal/api-test/test_ca.pem" # Optional CA certificate file for verifying server certificates.

# List of location configurations for proxying requests.
locations:
  - path: "^/test-ws$"
    target_url: "wss://echo.websocket.org"
    enable_websocket: true
    replace_path: true

  - path: "^/dito$" # Regex pattern to match the request path.
    target_url: https://httpbin.org/get
    enable_websocket: true # Enable or disable WebSocket support.
    # The target URL to which the request will be proxied.
    replace_path: true # Replace the matched path with the target URL.
    max_response_body_size: 52428800 # Maximum size of the response body in bytes (50 MB).
    disable_response_buffering: false # Disable response buffering for this location.

    additional_headers:
      # Additional headers to be added to the request.
      il-molise: non esiste ancora
    excluded_headers:
      #- Cookie # Headers to be excluded from the request.
    middlewares:
       - hello-plugin

  - path: "^/todos/(?:[1-9]|10)$" # Regex pattern to match the request path.
    target_url: https://jsonplaceholder.typicode.com/ # The target URL to which the request will be proxied.
    max_response_body_size: 90 # Medium limit - todos/1 passes (83 bytes), todos/2 fails (99 bytes)
    additional_headers:
      Host: jsonplaceholder.typicode.com # Additional headers to be added to the request.
    middlewares:
      #- hello-plugin
    excluded_headers:
      - Cookie # Headers to be excluded from the request.
    
  - path: "^/test-global-limit$" # Test endpoint to verify global limit usage
    target_url: https://jsonplaceholder.typicode.com/posts/1 # Returns ~292 bytes (should fail with 100KB global limit is not the issue)
    # No max_response_body_size specified - should use global limit of 100KB